# Use Python 3.12.3 slim image
FROM python:3.12.3-slim

# Set working directory in the container
WORKDIR /app

# Copy original game files into the container
COPY . /app

# Command to run the original game
CMD ["python", "originalgame.py"]
